[workspace]
resolver = "3"
members = ["angrr", "xtask"]

[workspace.package]
version = "0.2.2"
edition = "2024"
license = "MIT"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
homepage = "https://github.com/linyinfeng/angrr"
repository = "https://github.com/linyinfeng/angrr"
